### ISSUE TITLE
All commands stuck on loading

### ISSUE THREAD

**Issue by pgonzaleznetwork** [AyuSharma-dev/salesforce-md-info#8]
Hi there,

I'm trying to use this extension but none of the commands are working for me, they all get stuck as seen below

![Screenshot 2021-04-09 at 10 12 17](https://user-images.githubusercontent.com/8467087/114158112-40c94b80-991c-11eb-9169-87bbf9ad579b.png)

VS Code details

```
Version: 1.55.1
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T18:22:52.186Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

OS details

![Screenshot 2021-04-09 at 10 15 11](https://user-images.githubusercontent.com/8467087/114158360-7f5f0600-991c-11eb-9d01-11575cc04738.png)

It would be great if you could look into this as I could benefit from the extension.

Thanks!

**Comment by AyuSharma-dev** [comment]
Hey,
Can you please confirm if you have authorized your Salesforce ORG with the SFDX before? This extension has dependency over the SFDX as mentioned in the extension description.
Also, can you try once on a Windows machine if possible. I have not tested it on Mac yet.

**Comment by pgonzaleznetwork** [comment]
Yes it is. I can depoy, retrieve, etc with normal SFDX commands or via
vscode itself

Pablo

**Comment by AyuSharma-dev** [comment]
I checked out some other machines and it looks like something is not right about extension when it runs on the Mac machine. I am working on this. I will notify you once it's fixed. Thanks for reporting the issue.

**Comment by pgonzaleznetwork** [comment]
Sounds good, thanks!

Pablo

**Comment by AyuSharma-dev** [comment]
Hey, I have pushed some updates in the new version. Can you please update the extension and try again. Version is 0.0.6. 
Let me know how it goes.

**Comment by pgonzaleznetwork** [comment]
Thanks for the update! Unfortunately now I'm getting this error

_No data found with this name in Org. Either its deleted or you don't have access to it._

I'm able to access sobject information though by selecting an sobject from a soql query.

**Comment by AyuSharma-dev** [comment]
Seems another filePath issue. I have released a new version for this just now. The problem was with the FileName reading for the Mac. Please update to version 0.0.7 when it is available, I have published it will be available in some time.
Hopefully, it resolves the issue. Thanks.
